#! /bin/sh
set -m

cleanup() {
    echo "Stopping all processes..."
    pkill -P $$
}

BSPWM_PID=$(pgrep bspwm)

export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GTK_THEME=Materia-dark-compact
export XCURSOR_SIZE=24
export XCURSOR_THEME=Breeze_Light
export VISUAL=nano
export EDITOR=nano

xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
rclone mount school: $HOME/school &
rclone mount personal: $HOME/personal &
xorgrandbg -c 120 $HOME/Pictures/Backgrounds &
get-status | lemonbar -b -f "Roboto:style=Medium" -f 'Font Awesome 6 Free' -f 'Font Awesome 6 Brands' -f 'Font Awesome 6 Free Solid' -B \#a0222222 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config history_aware_focus   true
bspc config focus_by_distance     true

wait