#!/usr/bin/env bash
set -x
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# copy config files
cp -r ${SCRIPT_DIR}/home ${SCRIPT_DIR}/${USER}
cp -r ${SCRIPT_DIR}/${USER} /home/
rm -r ${SCRIPT_DIR}/${USER}
sudo cp -r ${SCRIPT_DIR}/etc ${SCRIPT_DIR}/usr ${SCRIPT_DIR}/bin /
# set correct amount of zram (ram*1.5)
ZRAM_SIZE="$(expr $(grep MemTotal /proc/meminfo | awk '{print $2}') \* 3 \/ 2)K"
echo "ACTION==\"add\", KERNEL==\"zram0\", ATTR{initstate}==\"0\", ATTR{comp_algorithm}=\"zstd\", ATTR{disksize}=\"$ZRAM_SIZE\", RUN=\"/usr/bin/mkswap -U clear %N\", TAG+=\"systemd\"" | sudo tee /etc/udev/rules.d/99-zram.rules
# apply gtk4 settings
gsettings set org.gnome.desktop.interface gtk-theme "Materia-dark-compact"
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
gsettings set org.gnome.desktop.interface cursor-theme "Breeze_Light"
gsettings set org.gnome.desktop.interface cursor-size 24
gsettings set org.gnome.desktop.interface font-name "Noto Sans Medium 12"
gsettings set org.gnome.desktop.interface font-rendering 'manual'
gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
gsettings set org.gnome.desktop.interface font-hinting 'medium'
gsettings set org.gnome.desktop.interface font-rgba-order 'rgb'
cd ${SCRIPT_DIR}/dwm
sudo make install
sudo make clean
# enable user configuration of fonts
cd /etc/fonts/conf.d
sudo ln -s /usr/share/fontconfig/conf.avail/50-user.conf
