#!/usr/bin/env bash
set -x
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cp -r ${SCRIPT_DIR}/home ${SCRIPT_DIR}/${USER}
cp -r ${SCRIPT_DIR}/${USER} /home/
rm -r ${SCRIPT_DIR}/${USER}
sudo cp -r ${SCRIPT_DIR}/etc ${SCRIPT_DIR}/usr /
cd ${SCRIPT_DIR}/dwm
make clean
sudo make install
# enable user configuration of fonts
cd /etc/fonts/conf.d
sudo ln -s /usr/share/fontconfig/conf.avail/50-user.conf
