#!/bin/bash
set -x
script_dir=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cp -r home/{*,.*} $HOME/
sudo cp -r etc/* "/etc/"

cd dwm
make clean
sudo make install

# enable user configuration of fonts
cd /etc/fonts/conf.d
sudo ln -s /usr/share/fontconfig/conf.avail/50-user.conf