#!/bin/bash
set -x
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# copy config files
cp -r ${SCRIPT_DIR}/home ${SCRIPT_DIR}/${USER}
cp -r ${SCRIPT_DIR}/${USER} /home/
rm -r ${SCRIPT_DIR}/${USER}
sudo cp -r ${SCRIPT_DIR}/etc ${SCRIPT_DIR}/usr ${SCRIPT_DIR}/bin /
# set correct amount of zram (ram*1.5)
ZRAM_SIZE="$(expr $(grep MemTotal /proc/meminfo | awk '{print $2}') \* 3 \/ 2)K"
echo "ACTION==\"add\", KERNEL==\"zram0\", ATTR{initstate}==\"0\", ATTR{comp_algorithm}=\"zstd\", ATTR{disksize}=\"$ZRAM_SIZE\", RUN=\"/usr/bin/mkswap -U clear %N\", TAG+=\"systemd\"" | sudo tee /etc/udev/rules.d/99-zram.rules
# check if yay is already installed otherwise install it
pacman -Qi yay || {
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si --noconfirm
    cd ..
    rm -rf yay
}
sudo pacman -Syu --noconfirm
sudo pacman -S --noconfirm --needed - < ${SCRIPT_DIR}/arch-pkg-list
yay -S --noconfirm --needed - < ${SCRIPT_DIR}/aur-pkg-list
# set gtk4 settings
gsettings set org.gnome.desktop.interface gtk-theme "Materia-dark-compact"
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
gsettings set org.gnome.desktop.interface cursor-theme "Breeze_Light"
gsettings set org.gnome.desktop.interface cursor-size 24
gsettings set org.gnome.desktop.interface font-rendering 'manual'
gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
gsettings set org.gnome.desktop.interface font-name "Noto Sans Medium 13"
gsettings set org.gnome.desktop.interface font-hinting 'medium'
gsettings set org.gnome.desktop.interface font-rgba-order 'rgb'
cd ${SCRIPT_DIR}/dwm
make clean
sudo make install
sudo systemctl enable NetworkManager.service
sudo systemctl enable bluetooth.service
sudo systemctl enable sshd.service
sudo systemctl enable zram.service
sudo systemctl enable sddm.service
sudo usermod -aG uucp,audio,video,input,optical,docker,storage ${USER}
chsh -s /bin/zsh
sudo chsh -s /bin/zsh

# enable user configuration of fonts
cd /etc/fonts/conf.d
sudo ln -s /usr/share/fontconfig/conf.avail/50-user.conf
