Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lrm"
    Option "ClickMethod" "bottonareas"
    Option "DisableWhileTyping" "off"
    Option "MiddleEmulation" "off"
    Option "NaturalScrolling" "on"
EndSection
