HISTFILE=~/.histfilezsh
HISTSIZE=5000
SAVEHIST=100000

setopt autocd extendedglob
unsetopt beep
bindkey -v

# Configure the prompt with embedded Solarized color codes
PROMPT='%F{#f7f7f7}%n%f%F{#f7f7f7}@%f%F{#f7f7f7}%m:%F{yellow}%~%f%F{#a0a0a0}$%f '
RPROMPT='%F{15}(%F{yellow}%D{%H:%M}%F{15})%f'

# zsh syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# zsh auto suggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
# zsh history substring
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
      bindkey '^[[A' history-substring-search-up
      bindkey '^[[B' history-substring-search-down
