#!/bin/sh

ON_HOUR=22
ON_MINUTE=45
OFF_HOUR=6
OFF_MINUTE=0
time_to_minutes() {
    hour=$1
    minute=$2
    printf $(( 10#$hour * 60 + 10#$minute ))
}
get_time_difference() {
    subtrahend=$1
    minuend=$2
    difference=$(( subtrahend - minuend ))
    if [ $difference -ge "0" ]; then
        printf $difference
    else
        printf $(( difference + 1440 ))
    fi
}
on_time=$(time_to_minutes $ON_HOUR $ON_MINUTE)
off_time=$(time_to_minutes $OFF_HOUR $OFF_MINUTE)
on_interval=$(get_time_difference $off_time $on_time)
while true; do
    current_hour=$(date +%H)
    current_minute=$(date +%M)
    current_time=$(time_to_minutes $current_hour $current_minute)
    time_since_on=$(get_time_difference $current_time $on_time)
    if [ "$time_since_on" -ge "$on_interval" ]; then
        if pidof hyprsunset; then
            kill $(pidof hyprsunset)
        fi
    else
        # Start hyprsunset if not running
        pidof hyprsunset || hyprsunset -t 1000 &
    fi
    sleep 1
done
