#!/usr/bin/env python3
import time
import os
import subprocess

# Replace with your tablet's device path
TABLET_DEVICE_PATH = "/dev/input/event21"

def main():
    last_activity = os.path.getmtime(TABLET_DEVICE_PATH)
    touchscreen_enabled = False
    subprocess.run(["hyprctl", "keyword", "input:touchdevice:enabled false"])
    print(f"Monitoring for changes in {TABLET_DEVICE_PATH}...")
    print("last modified:", time.localtime(last_activity))
    try:
        while True:
            last_activity = os.path.getmtime(TABLET_DEVICE_PATH)
            if touchscreen_enabled:
                if time.time() - last_activity < 100:
                    subprocess.run(["hyprctl", "keyword", "input:touchdevice:enabled false"])
                    touchscreen_enabled = False
                    print("Touchscreen disabled.")
            else:
                subprocess.run(["hyprctl", "keyword", "input:touchdevice:enabled true"])
                touchscreen_enabled = True
                print("Touchscreen enabled.")
            time.sleep(0.25)
    except KeyboardInterrupt:
        print("Exiting. Re-enabling touchscreen.")
        subprocess.run(["hyprctl", "keyword", "input:touchdevice:enabled true"])

if __name__ == "__main__":
    main()
