#!/usr/bin/env python3
import os
import time

if __name__ == "__main__":
    orientation = 0
    last_lid_state = "state:      open"
    os.system(f"hyprctl keyword monitor eDP-1, 1920x1200@60, 0x0, 1.25")
    while True:
        lid_state = open('/proc/acpi/button/lid/LID0/state', 'r').read().strip()
        if lid_state == "state:      open":
            # only turn on monitor once to allow override
            if lid_state != last_lid_state:
                os.system(f"hyprctl keyword monitor eDP-1, 1920x1200@60, 0x0, 1.25")
                last_lid_state = lid_state
        else:
            os.system(f"hyprctl keyword monitor eDP-1, disable")
            if lid_state != last_lid_state:
                last_lid_state = lid_state
        time.sleep(1)
