# example configuration

# configure release bind
release_bind = [ "KeyA", "KeyS", "KeyD", "KeyF" ]

# optional port (defaults to 4242)
port = 4242
# # optional frontend -> defaults to gtk if available
# # possible values are "cli" and "gtk"
# frontend = "gtk"

# list of authorized tls certificate fingerprints that
# are accepted for incoming traffic
[authorized_fingerprints]


# define a client on the left side with IP address 192.168.178.189
[top]
# The hostname is optional: When no hostname is specified,
# at least one ip address needs to be specified.
hostname = "minipc"
# activate this client immediately when lan-mouse is started
activate_on_startup = true
# ips for ethernet and wifi
ips = ["110.193.7.29", "10.0.27.31", "192.168.215.44"]
# optional port
port = 4242