[window]
  padding = { x = 5, y = 5 }

[colors.primary]
  background = "#1E1E1E"

[font]
  normal = { family = "SauceCodePro NF", style = "Regular" }
  bold = { family = "SauceCodePro NF", style = "Bold" }
  italic = { family = "SauceCodePro NF", style = "Italic" }
  bold_italic = { family = "SauceCodePro NF", style = "Bold Italic" }
  size = 16

[env]
  WINIT_X11_SCALE_FACTOR = "1.0"

[scrolling]
  multiplier = 3

# Handle Hyprland's universal clipboard shortcuts in the terminal itself.
[keyboard]
  bindings = [
    { key = "Insert", mods = "Control", action = "Copy" },
    { key = "Insert", mods = "Shift", action = "Paste" },
  ]
