# See logind.conf(5) for details.

[Login]
HandlePowerKey=suspend-then-hibernate
HandleLidSwitch=suspend-then-hibernate
HandleLidSwitchDocked=ignore
SleepOperation=suspend-then-hibernate
IdleAction=suspend-then-hibernate
IdleActionSec=300