#!/usr/bin/env python3
import subprocess
import time
import cmath

def get_accel():
    device_path = "/sys/bus/iio/devices/iio:device0/"
    accel_vals = [int(open(f"{device_path}in_accel_{a}_raw", 'r').read().strip()) for a in ['x', 'y']]
    return complex(-accel_vals[1], accel_vals[0])

def phase(x: complex):
    res = cmath.phase(x)
    if res < 0: res += cmath.tau
    return res

def get_0_to_tau(a: float):
    while a >= cmath.tau:
        a -= cmath.tau
    while a < 0:
        a += cmath.tau
    return a

def set_display_orientation(orientation: int):
    print("Setting orientation to", orientation)
    subprocess.run(["hyprctl", f"keyword monitor eDP-1, highres@highrr, 560x0, 1, transform, {orientation}"])
    subprocess.run(["hyprctl", "-r", f"keyword input:touchdevice:transform {orientation}"])
    subprocess.run(["hyprctl", "-r", f"keyword input:tablet:transform {orientation}"])

if __name__ == "__main__":
    orientation = 0
    set_display_orientation(orientation)
    while True:
        accel = get_accel()
        if abs(accel) > 2:
            new_orientation = int(2*(get_0_to_tau(phase(accel)+cmath.pi/4))/cmath.pi)
            if new_orientation != orientation:
                orientation = new_orientation
                set_display_orientation(orientation)
        time.sleep(0.5)
